name: build-prusaman
on:
  push:
jobs:
  build-pcm:
    name: Build PCM packages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-6.0-releases
          sudo apt-get update
          sudo apt-get -qq install --yes --no-install-recommends \
            kicad zip git python3 python3-pip moreutils
          python -m pip install -e .\[dev\]
      - name: Build PCM package
        run: make package pcm
      - name: Upload pcm package artifact
        uses: actions/upload-artifact@v2
        with:
          name: prusaman
          path: build/pcm/
          retention-days: 7
      - name: Upload Python package artifact
        uses: actions/upload-artifact@v2
        with:
          name: prusaman-python-package
          path: dist/
          retention-days: 7
